### PR TITLE
Update article.md & all SVGs

### PR DESCRIPTION
**Pull request by taleksina**
I hope it's not too much. I just wanted to add some Ukrainian vibes to the example. 💙💛

### CODE REVIEW

**Comment by taleksina** [comment]
Closes #551

**Review by tarasyyyk — APPROVED** [review]
Щиро вдячні за переклад!
Чудове перефразування, мені сподобалося :)

**Comment by tarasyyyk** [comment]
@all-contributors add @taleksina for translation.

**Comment by taleksina** [comment]
@tarasyyyk @alexandrtovmach
Thank you, guys! Now, you have inspired me to go on and make the UA tutorial rocks even more.

**Pull request merged**
